kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Black Code Format Check
  image: magic9669/network_cicd
  commands:
  - black . --check

- name: Precheck OSPF and BGP
  image: magic9669/network_cicd
  commands:
  - pytest test.py --disable-pytest-warnings -s

- name: Deploy Configurations
  image: magic9669/network_cicd
  environment:
    MY_PASS:
      from_secret: cisco
  commands:
  - python build.py
  when:
    branch:
    - master
    - main

trigger:
  event:
    exclude:
    - pull_request
