kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Install and deploy
  image: python
  environment:
    Test_Secret:
      from_secret: cisco
  commands:
  - pip3 install -r requirements.txt
  - python3 bat.py

trigger:
  branch:
    exclude:
    - main
    - master
