---
inventory:
  plugin: SimpleInventory
  options:
    host_file: "./configs/hosts.yaml"
    group_file: "./configs/groups.yaml"
    ssl_verify: false
runner:
  plugin: threaded
  options:
    num_workers: 10
